#!/usr/bin/env bash

brew install zsh

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles

alias GITCLONE="git clone --depth=1"

cd $HOME
rm -rf $DOTFILES
mkdir $DOTFILES
cd $DOTFILES

git init
git remote add origin git@github.com:mj111/dotfiles.git
git pull origin master
git submodule update --init --recursive

rm -rf \
  $DOTFZF \
  $DOTLOCAL \
  $HOME/.bashrc \
  $HOME/.gitconfig \
  $HOME/.zshrc

ln -s $DOTFILES/bashrc $HOME/.bashrc
ln -s $DOTFILES/gitconfig $HOME/.gitconfig
ln -s $DOTFILES/zshrc $HOME/.zshrc

mkdir -p \
  $DOTLOCAL

GITCLONE https://github.com/junegunn/fzf.git $DOTFZF
$DOTFZF/install --key-bindings --completion --no-update-rc

GITCLONE https://github.com/zsh-users/zsh-autosuggestions $DOTLOCAL/zsh-autosuggestions
GITCLONE https://github.com/zsh-users/zsh-completions.git $DOTLOCAL/zsh-completions
GITCLONE https://github.com/zsh-users/zsh-history-substring-search.git $DOTLOCAL/zsh-history-substring-search
GITCLONE https://github.com/zsh-users/zsh-syntax-highlighting.git $DOTLOCAL/zsh-syntax-highlighting

# theme
git clone https://github.com/geometry-zsh/geometry $DOTLOCAL/geometry
cd $DOTLOCAL/geometry
git submodule update --init --recursive


cd $HOME
rm -f $HOME/.zcompdump*

echo
echo 'DONEZO!!~!'
