#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles

alias GITCLONE="git clone --depth=1"

cd $HOME
rm -rf $DOTFILES
mkdir $DOTFILES
cd $DOTFILES

git init
git remote add origin git@github.com:mj111/dotfiles.git
git pull origin master
git submodule update --init --recursive

rm -rf \
  $DOTFZF \
  $DOTLOCAL \
  $HOME/.gitconfig \
  $HOME/.zshrc

ln -s $DOTFILES/gitconfig $HOME/.gitconfig
ln -s $DOTFILES/zshrc $HOME/.zshrc

mkdir -p \
  $DOTLOCAL \
  $HOME/.local/share/vim/{swap,undo} \
  $HOME/.vim/pack/plugins/start

GITCLONE https://github.com/junegunn/fzf.git $DOTFZF
$DOTFZF/install --key-bindings --completion --no-update-rc

GITCLONE https://github.com/zsh-users/zsh-completions.git $DOTLOCAL/zsh-completions
GITCLONE https://github.com/zsh-users/zsh-history-substring-search.git $DOTLOCAL/zsh-history-substring-search
GITCLONE https://github.com/zsh-users/zsh-syntax-highlighting.git $DOTLOCAL/zsh-syntax-highlighting

GITCLONE https://github.com/w0rp/ale.git $HOME/.vim/pack/plugins/start/ale
GITCLONE https://github.com/junegunn/fzf.vim.git $HOME/.vim/pack/plugins/start/fzf

cd $HOME
rm -f $HOME/.zcompdump*

echo
echo 'DONEZO!!~!'
